/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reserva.de.habitacion.de.hotel;

import java.awt.Graphics;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Miguel
 */
public class Home extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Home
     */
    public Home() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        SaveNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Correo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Numero = new javax.swing.JTextField();
        jButton_mensaje = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Habitaciones = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        Combobox_habitacion = new javax.swing.JComboBox<>();
        Jtxt_Fecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Jtxt_fechasalida = new javax.swing.JTextField();
        jButton_mensajeReserva = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maxresdefault-620x349.jpg"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 310));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 260));

        jTabbedPane1.addTab("Inicio", jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nombre:");
        jPanel3.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        SaveNombre.setName("txt_nombre"); // NOI18N
        SaveNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNombreActionPerformed(evt);
            }
        });
        jPanel3.add(SaveNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 270, -1));

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel1.setText("ID: ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 30, -1));

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel3.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 270, -1));

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel2.setText("Correo:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, -1));
        jPanel3.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 270, -1));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel3.setText("N. de Telefono:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        jPanel3.add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 230, -1));

        jButton_mensaje.setBackground(new java.awt.Color(0, 0, 102));
        jButton_mensaje.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jButton_mensaje.setForeground(new java.awt.Color(255, 255, 255));
        jButton_mensaje.setText("Registro");
        jButton_mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mensajeActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images.jpeg"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 220, 200));

        jTabbedPane1.addTab("Usuario", jPanel3);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla_Habitaciones.setBackground(new java.awt.Color(255, 204, 153));
        Tabla_Habitaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tabla_Habitaciones.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Tabla_Habitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Simple", "150.00 ", "Una cama, Desayuno Buffet"},
                {"2", "Doble ", "200.00", "Dos camas, Desayuno Buffet, Aire acondicionado"},
                {"3", "Familiar", "300.00", "Cuatro camas, Desayuno Buffet, Aire Acondicionado"},
                {"4", "Suite", "500.00", "Salon Recreativo, Oficina, Atencion 24 horas, Aire acondicionado"}
            },
            new String [] {
                "Num. Habitacion", "Tipo", "Precio", "Detalles"
            }
        ));
        jScrollPane2.setViewportView(Tabla_Habitaciones);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 110));

        jLabel4.setText("Habitacion: ");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        Combobox_habitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        Combobox_habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combobox_habitacionActionPerformed(evt);
            }
        });
        jPanel5.add(Combobox_habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        Jtxt_Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_FechaActionPerformed(evt);
            }
        });
        jPanel5.add(Jtxt_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 170, -1));

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel5.setText("Fecha de Llegada:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel6.setText("Fecha de Salida: ");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        Jtxt_fechasalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxt_fechasalidaActionPerformed(evt);
            }
        });
        jPanel5.add(Jtxt_fechasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 170, -1));

        jButton_mensajeReserva.setBackground(new java.awt.Color(0, 0, 102));
        jButton_mensajeReserva.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jButton_mensajeReserva.setForeground(new java.awt.Color(255, 255, 255));
        jButton_mensajeReserva.setText("Reserva");
        jButton_mensajeReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mensajeReservaActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_mensajeReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("(dd/MM/yyyy)");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        Salir.setBackground(new java.awt.Color(0, 0, 102));
        Salir.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel5.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jTabbedPane1.addTab("Reservacion", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNombreActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_SaveNombreActionPerformed

    private void jButton_mensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mensajeActionPerformed
        // TODO add your handling code here:
        String nombre = SaveNombre.getText();
    String id = ID.getText();
    String correo = Correo.getText();
    String numero = Numero.getText();
        
        JOptionPane.showMessageDialog(this, "Registro completado: \nNombre: " + nombre + "\nID: " + id + "\nCorreo: " + correo + "\nTeléfono: " + numero);
    }//GEN-LAST:event_jButton_mensajeActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void Jtxt_FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_FechaActionPerformed
        String fechaIngresada = Jtxt_Fecha.getText();
    
        // Definir el formato de la fecha
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);  // validar que el formato sea correcto

        try {
            sdf.parse(fechaIngresada);
            
            JOptionPane.showMessageDialog(null, "Fecha Ingresada con éxito: " + fechaIngresada);
        } catch (ParseException e) {

            JOptionPane.showMessageDialog(null, "Ingrese la fecha en el formato dd/MM/yyyy");
        }   
    }//GEN-LAST:event_Jtxt_FechaActionPerformed

    private void Jtxt_fechasalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxt_fechasalidaActionPerformed
        String fechaSalida = Jtxt_fechasalida.getText();
    
    // Definir el formato de la fecha
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    sdf.setLenient(false);  // Para que valide estrictamente el formato

    try {
        sdf.parse(fechaSalida);
        
        JOptionPane.showMessageDialog(this, "Fecha ingresada con exito" + fechaSalida);
        
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Ingrese la fecha de salida en el formato dd/MM/yyyy");
    }
    }//GEN-LAST:event_Jtxt_fechasalidaActionPerformed

    private void jButton_mensajeReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mensajeReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_mensajeReservaActionPerformed

    private void Combobox_habitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combobox_habitacionActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_Combobox_habitacionActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        JOptionPane.showMessageDialog(this,"ESPERAMOS VERTE PRONTO");
        System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combobox_habitacion;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Jtxt_Fecha;
    private javax.swing.JTextField Jtxt_fechasalida;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField Numero;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField SaveNombre;
    private javax.swing.JTable Tabla_Habitaciones;
    private javax.swing.JButton jButton_mensaje;
    private javax.swing.JButton jButton_mensajeReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}

